### ISSUE TITLE
Why is UPWARD_MESSAGES not reset?

### ISSUE THREAD

**Issue by apopiak** [shaunxw/xcm-simulator#35]
https://github.com/shaunxw/xcm-simulator/blob/651af78d6d7521dc76e1f6bb257af485f8a454c7/xcm-emulator/src/lib.rs#L306
Resets the `DOWNWARD_MESSAGES` queue, but not the upward one. This seems like the reset could be incomplete.

**Comment by shaunxw** [comment]
as far as I can remember, messages should all be consumed after each ext execution, but downward messages is a special case that different from ump and hrmp. please feel free to add a unit test to check if it is indeed an bug
