### ISSUE TITLE
Question: Using a local version of Polkadot with `xcm-emulator`

### ISSUE THREAD

**Issue by darkforest0202** [shaunxw/xcm-simulator#53]
Hello!!!

i would like to use a local version of Polkadot so i can log custom debug messages in the executor and builder. I tried redirecting all the polkadot pallets to my local repository but when i compile tons of errors and unmet trait bounds appear specially with the `xcm-emulator`. Is this possible?

**Comment by shaunxw** [comment]
Yes, it is possible. The compile error is probably because your local repo doesn't have the same version of upstream Substrate dependencies with the `xcm-emulator` you used.

**Comment by darkforest0202** [comment]
> Yes, it is possible. The compile error is probably because your local repo doesn't have the same version of upstream Substrate dependencies with the `xcm-emulator` you used.

Thanks for @shaunxw ! actually i'm using `release-v0.9.42` and `polkadot-v0.9.42` for all the imports, should i specify the commits as well using `rev`?

**Comment by shaunxw** [comment]
It should work with the same polkadot release branch. I would suggest to double check your cargo lock file to see if there are multiple substrate versions used.
